### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by trivigy** [cpp-netlib/uri#108]

**Comment by mikhailberis** [comment]
Yes, though only partially since I’m doing the maintenance on the side
only. Why do you ask?

**Comment by glynos** [comment]
It’s sleeping. I have written an improved implementation based on the whatwg document but I haven’t shared it yet: https://github.com/glynos/uri/tree/whatwg_spec

It includes breaking changes and isn’t fully complete, but may be an improvement.

Please let us know if you’re interested in contributing.

**Comment by trivigy** [comment]
@mikhailberis The reason I was asking was because I need some sort of a uri library in my project and was looking what to use. I am trying to avoid really hard from start one myself. Too much time on replicating what other have already done better.

@glynos Happy to contribute and help out anyway I can. Just create an issue, write down what you need and I'll be able to figure it out. Also I would definitely rather use the whatwg based implementation.

**Comment by glynos** [comment]
I've partially implemented a new parser based on the whawg spec on a branch on my own fork:

https://github.com/glynos/uri/tree/whatwg_spec

It's about 90% of the way there, but the interface has drastically changed. If you want to take a look and comment I would be grateful.

I intend to continue working on the implementation, I think only encoding issues remain ("only"). Then, I'll tidy up the interface and implement URL writing and serializing. With a bit of momentum, if it's still good, It's possible that it could be robust enough by the end of the summer.

**Comment by trivigy** [comment]
I am in a crunch right now with my current work but if you give me a few days I'll give it a read.

**Comment by glynos** [comment]
There's no hurry.
