### ISSUE TITLE
throw network::uri_syntax_error when contains square brackets

### ISSUE THREAD

**Issue by litao-buptsse** [cpp-netlib/uri#110]
case: http://www.example.com/path/?key1=value1&key2=val[ue2

**Comment by litao-buptsse** [comment]
@glynos Hi glynos, I am using cpp-netlib/uri to re-implement python urlparse for better performance. I meet the square brackets case and want to quickly skip verify it. Can you give me some advice?

**Comment by glynos** [comment]
@litao-buptsse, in the current implementation, the possibility to skip elements is not given. If you need to adapt the parser, the only thing I can suggest is to fork the repo.

I have started exploring an implementation for a parser that follows the WhatWG spec: https://github.com/glynos/uri/tree/whatwg_spec. It's still in progress but it might be a better opportunity to do what you are asking.

**Comment by litao-buptsse** [comment]
@glynos thanks for your advice
