### ISSUE TITLE
Copy constructor fails!!!

### ISSUE THREAD

**Issue by jean-m-cyr** [cpp-netlib/uri#114]
```
network::uri u("http://google.com");
cerr << u.host() << '\n';
u = network::uri("http://microsoft.com");
cerr << u.host() << '\n';
```

yields:

```
google.com
microsoft.

```

**Comment by glynos** [comment]
I saw your comments on the mailing list, and it seems this refers to an implementation of the URI library that is several years old. A quick check has shown that the current implementation behaves as expected.
