### ISSUE TITLE
Error on removing adjacent slashes

### ISSUE THREAD

**Issue by ncnxc** [cpp-netlib/uri#122]
Hello,

Adjacent slashes are not removed in some cases.
Please find the test case for the problem below:
```
TEST(uri_normalization_test, path_double_dash2) {
  network::uri instance("http://www.example.com/abc//elementary");
  ASSERT_EQ("http://www.example.com/abc/elementary",
            instance.normalize(network::uri_comparison_level::syntax_based).string());
}
```

When I run `make test`, CTest is failing with following output:
> /home/user/cpp-netlib-uri_test/test/uri_normalization_test.cpp:143: Failure
Value of: instance.normalize(network::uri_comparison_level::syntax_based).string()
  Actual: "http://www.example.com/abc//elementary"
Expected: "http://www.example.com/abc/elementary"
[  FAILED  ] uri_normalization_test.path_double_dash2 (0 ms)

If we try to normalize http://www.example.com/abc//elementary, the normalized value should be http://www.example.com/abc/elementary.

Thanks.

**Comment by glynos** [comment]
@ncnxc: thanks for the report. Can you review this PR to confirm that it fixes your issue?

**Comment by glynos** [comment]
I took this suggestion and indeed it is much cleaner. You can find the code in the last commit.

**Comment by ncnxc** [comment]
Thank you very much. I am looking forward for v1.0.4 release :)

**Comment by glynos** [comment]
There you go.
