### ISSUE TITLE
network::uri_builder::uri() method crashes with special user_info string

### ISSUE THREAD

**Issue by johnco3** [cpp-netlib/uri#48]
I tried setting the following as basically blank userid and password fields for the FTP credentials.  The  mlfBldr.uri() crashes with the expression string iterator + offset out of range.

        static const std::string gUserInfo(":");
        network::uri_builder mlfBldr;
        mlfBldr.scheme("ftp").host(nicHost).user_info(gUserInfo);
        auto uri = mlfBldr.uri();

The code breaks in the 3rd last line of the snuppet below from uri.cpp (from the uri subproject).  I was expecting to either have an error indicating that the ":" paramter was illegal or am pretty sure that the problem is due to the while ((':' == *it) || ('/' == *it)) as the code there does not expect a : to follow (as is the case when the userid password are set to null. as per calling the method uri_builder::user_info(":") - this leaves the iterator pointing to the 3rd occurrence of a colon in this URI.  Also if I change the userid/password to " :" leaving a single space in for the userid then things work fine.

    auto it = std::begin(uri_);
    if (scheme) {
      uri_parts_.scheme.reset(
          copy_range(std::begin(*scheme), std::end(*scheme), it));
      // ignore ://
      while ((':' == *it) || ('/' == *it)) {
        ++it;
      }
    }

    if (user_info) {
      uri_parts_.hier_part.user_info.reset(
          copy_range(std::begin(*user_info), std::end(*user_info), it));
      ++it;  // ignore @
    }

    if (host) {
      uri_parts_.hier_part.host.reset(
          copy_range(std::begin(*host), std::end(*host), it));
    }

**Comment by cmbrandenburg** [comment]
I have reproduced this bug. The `empty_username` test in `uri_builder_test.cpp` fails for me. I'm running Visual Studio 2013, using the `nmake` generator.

I have a patch and can submit a pull request soon.

**Comment by cmbrandenburg** [comment]
Should this issue be closed?
