### ISSUE TITLE
URI builder doesn't accept non-array string literals

### ISSUE THREAD

**Issue by cmbrandenburg** [cpp-netlib/uri#68]
The `uri_builder` class rejects pointer-type string literals with a compiler error. Instead, string literals must be of array type.

    const char* const p = "http";
    const char* const q = "foo";
    const auto u =
      network::uri_builder()
      .scheme(p)           // ERROR: 'impl' uses undefined struct 'network::detail::translate_impl<Source>'
      .host("example.com") // OK: string literal is array type
      .path(*reinterpret_cast<const char(*)[1]>(q)) // OK: cast to array type
      .uri();

This problem affects all functions that pass through the `translate_impl` trait, which is implemented for `std::string` and `char` arrays—but not `char` pointers.

**Comment by glynos** [comment]
Fixed in #80.
