### ISSUE TITLE
Missing install rules

### ISSUE THREAD

**Issue by Plaristote** [cpp-netlib/uri#84]
There's no install rule for cpp-netlib/uri.

When installing cpp-netlib, conforming to the `README.rst` from cpp-netlib/cpp-netlib, files such as `network/uri/uri.hpp` aren't installed.

Trying to compile an application using cpp-netlib's server results in a message such as this:
```
boost/network/protocol/http/impl/request.hpp:20:31: fatal error: network/uri/uri.hpp: No such file or directory
```

I'm going to work around it, but perhaps there should be an install rule for cpp-netlib/uri, or perhaps the CMakeLists from cpp-netlib/cpp-netlib should take care of installing these files.

**Comment by glynos** [comment]
Thanks, @Plaristote, I appreciate the input
