### ISSUE TITLE
uri::has_host() returns true for "http://"

### ISSUE THREAD

**Issue by creste** [cpp-netlib/uri#87]
If the URI is "http://" then uri::has_host() returns true even though there is no host.  I expected it to return false.

**Comment by glynos** [comment]
"http://" is not a valid URI. You are correct that this is an error, but the parser should fail.

**Comment by byteboon** [comment]
"http://user@" will also return true for uri::has_host()

**Comment by glynos** [comment]
Both "http://" and "http://user@" are invalid URIs, and a syntax error is thrown for each.
