### ISSUE TITLE
`make install` results in nested include directory

### ISSUE THREAD

**Issue by shlevy** [cpp-netlib/uri#90]
If I build with cmake, make, make install, I get `include/include/network` in my install prefix.

**Comment by glynos** [comment]
What branch are you working on?

**Comment by shlevy** [comment]
master

**Comment by shlevy** [comment]
Building using standard cmake build script in nixpkgs: https://github.com/NixOS/nixpkgs/blob/ecb596b898bcf3992ab3b90fa0b301153801f810/pkgs/development/libraries/uri/default.nix

**Comment by glynos** [comment]
Fixed:

https://github.com/georgi-d/uri/commit/12056db3e218dd9a9ef5c08a713bf1c968f7a4b2
